name: Tests & Lint
on:
  - push
  - pull_request
jobs:
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn lint
      - run: yarn build --if-present
      - run: yarn test
